name:                odmatrix-ffi
version:             0.1.0.0
github:              "githubuser/odmatrix-ffi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/odmatrix-ffi#readme>

dependencies:
- base >= 4.7 && < 5
- odmatrix

library:
  source-dirs: src

# executables:
#   odmatrix-ffi-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - odmatrix-ffi

# tests:
#   odmatrix-ffi-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - odmatrix-ffi

verbatim: |
  foreign-library odmatrix-ffi
    type:               native-shared
    lib-version-info:   0:0:1
    other-modules:      TestModule
    build-depends:      base >= 4.7 && < 5
                      , odmatrix
    hs-source-dirs:     src
    c-sources:          csrc/MyForeignLibWapper.c
    default-language:   Haskell2010
